
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "wlqckrpmafyicxqhkeiw"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Default is "public".
schemas = ["public"]

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually delivered to emails,
# but instead can be viewed in a web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
# Port to use for the email testing server SMTP port.
smtp_port = 54325
# Port to use for the email testing server POP3 port.
pop3_port = 54326

[storage]
# The maximum file size allowed (in bytes).
file_size_limit = 52428800

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:5173"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["http://localhost:3000", "http://localhost:5173"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Configure Edge Functions
[functions]
# Port to use for Edge Functions emulator.
port = 54321
# Supabase functions to serve.
serve = ["influencer-notification"]

# Configure Supabase CLI workflow.
[workflows]
[workflows.default]
[workflows.default.deploy]
# Everything that doesn't match the patterns in 'ignore_files' will be deployed.
ignore_files = ["README.md"]
