
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlqckrpmafyicxqhkeiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndscWNrcnBtYWZ5aWN4cWhrZWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDYwNTcsImV4cCI6MjA1ODY4MjA1N30.OIrwgRT4jt49D5mfM97EbqEeyJZATxZL4Iy6qgB298w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    }
  }
});
